name: "Deploy to Heroku - git-crypt"
description: "Deploy an app to Heroku"
branding:
  icon: "upload-cloud"
  color: "purple"
inputs:
  heroku_api_key:
    description: "This will be used for authentication. You can find it in your heroku homepage account settings"
    required: true
  heroku_email:
    description: "Email that you use with heroku"
    required: true
  heroku_app_name:
    description: "The appname to use for deploying/updating"
    required: true
  buildpack:
    description: "An optional buildpack to use when creating the heroku application"
    required: false
  branch:
    description: "The branch that you would like to deploy to Heroku"
    default: "HEAD"
    required: false
  dontuseforce:
    description: "Set this to true if you don't want to use --force when switching branches"
    default: "false"
    required: false
  dontautocreate:
    description: "Set this to true if you don't want to automatically create the Heroku app"
    default: "false"
    required: false
  usedocker:
    description: "Will deploy using Dockerfile in project root."
    default: "false"
    required: false
  docker_heroku_process_type:
    description: "Type of heroku process (web, worker, etc). This option only makes sense when usedocker enabled"
    default: "web"
    required: false
  docker_build_args:
    description: "A list of args to pass into the Docker build. This option only makes sense when usedocker enabled"
    required: false
  appdir:
    description: "Set if your app is located in a subdirectory."
    default: ""
    required: false
  healthcheck:
    description: "A URL to which a healthcheck is performed (checks for 200 request)"
    required: false
    default: ""
  checkstring:
    description: "Value to check for when conducting healthcheck request"
    required: false
    default: ""
  delay:
    description: "Time (in seconds) to wait before performing healthcheck"
    required: false
    default: "0"
  procfile:
    description: "Contents of the Procfile to save and deploy"
    required: false
    default: ""
  rollbackonhealthcheckfailed:
    description: "When set to true this will attempt to rollback to the previous release if the healthcheck fails"
    required: false
    default: "false"
  env_file:
    description: "Path to an localized env file"
    required: false
    default: ""
  justlogin:
    description: "Set to true if you want the action to just login to Heroku and nothing else"
    required: false
    default: "false"
  region:
    description: "The region in which you would like to deploy a server"
    required: false
    default: ""
  stack:
    description: "Set stack of your heroku app if you need to change.Default : heroku-20"
    required: false
    default: ""
  team:
    description: "If deploying to an organization, then specify the name of the team or organization here"
    required: false
    default: ""
  git_crypt_key:
    description: "git-crypt secret key"
    required: false
    default: ""
outputs:
  status:
    description: "The Success/Failure of the action"
runs:
  using: "node20"
  main: "index.js"
