name: Deploy to Heroku
description: Deploy an app to Heroku
branding:
  icon: upload-cloud
  color: purple
inputs:
  heroku_api_key:
    description: This will be used for authentication. You can find it in your
      heroku homepage account settings
    required: true
  heroku_email:
    description: Email that you use with heroku
    required: true
  heroku_app_name:
    description: The appname to use for deploying/updating
    required: true
  buildpack:
    description: An optional buildpack to use when creating the heroku application
    required: false
  branch:
    description: The branch that you would like to deploy to Heroku
    default: main
    required: false
  dontuseforce:
    description: Set this to true if you don't want to use --force when switching branches
    default: "false"
    required: false
  dontautocreate:
    description: Set this to true if you don't want to automatically create the Heroku app
    default: "false"
    required: false
  usedocker:
    description: Will deploy using Dockerfile in project root.
    default: "false"
    required: false
  docker_heroku_process_type:
    description: Type of heroku process (web, worker, etc). This option only makes
      sense when usedocker enabled
    default: web
    required: false
  docker_build_args:
    description: A list of args to pass into the Docker build. This option only
      makes sense when usedocker enabled
    required: false
  appdir:
    description: Set if your app is located in a subdirectory.
    default: ""
    required: false
  healthcheck:
    description: A URL to which a healthcheck is performed (checks for 200 request)
    default: ""
    required: false
  checkstring:
    description: Value to check for when conducting healthcheck request
    default: ""
    required: false
  delay:
    description: Time (in seconds) to wait before performing healthcheck
    default: "0"
    required: false
  procfile:
    description: Contents of the Procfile to save and deploy
    default: ""
    required: false
  rollbackonhealthcheckfailed:
    description: When set to true this will attempt to rollback to the previous
      release if the healthcheck fails
    default: "false"
    required: false
  env_file:
    description: Path to an localized env file
    default: ""
    required: false
  justlogin:
    description: Set to true if you want the action to just login to Heroku and nothing else
    default: "false"
    required: false
  region:
    description: The region in which you would like to deploy a server
    default: ""
    required: false
  stack:
    description: Set stack of your heroku app if you need to change.Default heroku-20
    default: ""
    required: false
  team:
    description: If deploying to an organization, then specify the name of the team
      or organization here
    default: ""
    required: false
outputs:
  status:
    description: The Success/Failure of the action
runs:
  using: docker
  image: Dockerfile
  env:
    ga_heroku_api_key: ${{ inputs.heroku_api_key }}
    ga_heroku_email: ${{ inputs.heroku_email }}
    ga_heroku_app_name: ${{ inputs.heroku_app_name }}
    ga_buildpack: ${{ inputs.buildpack }}
    ga_branch: ${{ inputs.branch }}
    ga_dontuseforce: ${{ inputs.dontuseforce }}
    ga_dontautocreate: ${{ inputs.dontautocreate }}
    ga_usedocker: ${{ inputs.usedocker }}
    ga_docker_heroku_process_type: ${{ inputs.docker_heroku_process_type }}
    ga_docker_build_args: ${{ inputs.docker_build_args }}
    ga_appdir: ${{ inputs.appdir }}
    ga_healthcheck: ${{ inputs.healthcheck }}
    ga_checkstring: ${{ inputs.checkstring }}
    ga_delay: ${{ inputs.delay }}
    ga_procfile: ${{ inputs.procfile }}
    ga_rollbackonhealthcheckfailed: ${{ inputs.rollbackonhealthcheckfailed }}
    ga_env_file: ${{ inputs.env_file }}
    ga_justlogin: ${{ inputs.justlogin }}
    ga_region: ${{ inputs.region }}
    ga_stack: ${{ inputs.stack }}
    ga_team: ${{ inputs.team }}
